version: '3.8'

services:
  # Test environment with PHP 5.3
  wordpress-test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      - WP_TESTS_DIR=/tmp/wordpress-tests-lib
      - WP_CORE_DIR=/tmp/wordpress
      - WP_TESTS_DB_HOST=db-test
      - WP_TESTS_DB_USER=root
      - WP_TESTS_DB_PASS=wordpress
      - WP_TESTS_DB_NAME=wordpress_test
      - WP_TESTS_DB_PORT=3306
    volumes:
      - .:/var/www/html/wp-content/plugins/screenly-cast
      - ./phpunit.xml:/var/www/html/wp-content/plugins/screenly-cast/phpunit.xml
    depends_on:
      - db-test

  db-test:
    image: mysql:5.6
    platform: linux/amd64
    tmpfs:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
