services:
  # Test environment with PHP 5.3
  wordpress-test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    volumes:
      - .:/var/www/html/wp-content/plugins/screenly-cast-root
    depends_on:
      db-test:
        condition: service_healthy

  db-test:
    image: mysql:5.5
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress_test
    tmpfs:
      - /var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-pwordpress"]
      interval: 1s
      timeout: 5s
      retries: 30
      start_period: 10s
