name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php-quality:
    name: PHP
    runs-on: ubuntu-latest
    container: php:8.2-cli
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y git unzip
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          composer install

      - name: Run PHP CodeSniffer
        run: ./vendor/bin/phpcs --standard=.phpcs.xml.dist .

  style-quality:
    name: CSS/JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run CSS linter
        run: npm run lint:css -- --formatter=github

      - name: Run JS linter
        run: npm run lint:js -- --format=stylish