name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install PHP and Composer
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli
          curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

      - name: Install dependencies
        run: composer install

      - name: Run PHP CodeSniffer
        run: composer run lint:php

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js dependencies
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint '**/*.md' --ignore node_modules --config .markdownlint.json