name: Code Quality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  php-quality:
    name: PHP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run PHP CodeSniffer
        run: |
          docker compose build --build-arg PHP_VERSION=8.2 wordpress-test
          docker compose run --rm wordpress-test ./vendor/bin/phpcs --standard=.phpcs.xml.dist . --report=checkstyle | cs2pr

  style-quality:
    name: CSS/JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run CSS linter
        run: npm run lint:css -- --formatter=string

      - name: Run JS linter
        run: npm run lint:js -- --format=github