name: Generate WordPress Plugin Package

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Package WordPress Plugin
        run: |
          ./bin/build.sh

      - name: Upload Package As Artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenly-cast-plugin
          path: dist/screenly-cast.zip
          compression-level: 0
