name: Generate WordPress Plugin Package

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Package WordPress Plugin
        run: |
          ./bin/build.sh

      - name: Upload Package As Artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenly-cast-plugin
          path: artifact/screenly-cast.zip
          retention-days: 5
