name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  release:
    name: Release to WordPress.org
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-release-${{ hashFiles('tests/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-buildx-release-
          ${{ runner.os }}-buildx-

    - name: Build release
      run: |
        # First run tests with dev dependencies
        docker buildx build \
          --file tests/Dockerfile \
          --cache-from type=local,src=/tmp/.buildx-cache \
          --cache-to type=local,dest=/tmp/.buildx-cache,mode=max \
          --load \
          -t wordpress-test .
        docker compose run --rm wordpress-test sh -c "composer install && composer test"

        # Clean and build for release without dev dependencies
        rm -rf vendor
        docker compose run --rm wordpress-test sh -c "composer install --no-dev --optimize-autoloader"
        ./bin/build.sh

    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: screenly-cast
        BUILD_DIR: build/screenly-cast