name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']
        wordpress: ['6.4', '6.3', '6.2']
        exclude:
          - wordpress: '6.4'
            php: '7.4'
          - wordpress: '6.3'
            php: '7.4'

    steps:
      - uses: actions/checkout@v3

      - name: Build and run tests
        run: |
          docker compose build \
            --build-arg PHP_VERSION=${{ matrix.php }} \
            wordpress-test
          WP_VERSION=${{ matrix.wordpress }} docker compose up \
            --exit-code-from wordpress-test \
            wordpress-test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./build/logs/clover.xml
          fail_ci_if_error: true