name: Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2']
        wordpress-versions: ['latest', '6.4', '6.3', '6.2']

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, xml, mysql, zip
          coverage: xdebug
          tools: composer, phpcs, phpunit

      - name: Install WordPress Test Suite
        run: |
          bash bin/install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wordpress-versions }}

      - name: Install Dependencies
        run: |
          composer install --prefer-dist --no-progress

      - name: Run PHP CodeSniffer
        run: |
          phpcs --standard=WordPress ./screenly-cast

      - name: Run PHPUnit Tests
        run: |
          phpunit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./clover.xml